title: Alphafold and Protein Folding
show_downloads: true
description: <a href="https://eckao.github.io/compbio-alphafold-project/">Return To Homepage</a>
google_analytics:
theme: jekyll-theme-cayman
